# Generated by Django 3.0.2 on 2020-02-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory_name', models.CharField(max_length=20, unique=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(help_text='Enter Student ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('surname', models.CharField(help_text='Enter Family Name', max_length=20)),
                ('other_name', models.CharField(blank=True, help_text='Enter Other Name', max_length=20)),
                ('father_alive', models.BooleanField(blank=True, default=True, help_text='Is the father alive?')),
                ('mother_alive', models.BooleanField(blank=True, default=True, help_text='Is the mother alive?', null=True)),
                ('father_first_name', models.CharField(blank=True, help_text="Enter the first name of the student's male guardian", max_length=20)),
                ('father_surname', models.CharField(blank=True, max_length=20)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_phone', models.IntegerField(null=True)),
                ('father_premium', models.BooleanField(blank=True, default=False, help_text='Do not edit this')),
                ('mother_first_name', models.CharField(blank=True, help_text="Enter the first name of the student's female guardian", max_length=20)),
                ('mother_surname', models.CharField(blank=True, max_length=20)),
                ('mother_email', models.EmailField(max_length=254, null=True)),
                ('mother_phone', models.IntegerField(null=True)),
                ('mother_premium', models.BooleanField(blank=True, default=False, help_text='Do not edit this')),
                ('date_of_birth', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('admission_date', models.DateField(auto_now=True, null=True)),
                ('is_enrolled', models.BooleanField(default=True, help_text='Is the student enrolled?')),
                ('home_country', models.CharField(blank=True, help_text='Enter home County', max_length=20)),
                ('home_county', models.CharField(blank=True, help_text='Enter home County', max_length=20)),
                ('home_town', models.CharField(blank=True, help_text='Enter home Town', max_length=20)),
                ('religion', models.CharField(blank=True, max_length=10)),
                ('health', models.TextField(blank=True, default='Good', help_text='Enter health status or complications', max_length=500)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('class_ns', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='academics.Classes')),
                ('dormitory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='students.Dormitories')),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('issue', models.TextField(max_length=150)),
                ('treatment', models.TextField(blank=True, max_length=150)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'ordering': ['date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('issue', models.TextField(max_length=300)),
                ('outcome', models.TextField(blank=True, max_length=150)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'ordering': ['date', 'student'],
            },
        ),
    ]
