# Generated by Django 3.0.2 on 2020-02-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20200202_1646'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_ns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.Classes'),
        ),
    ]
