# Generated by Django 3.0.2 on 2020-02-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200202_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Dormitories'),
        ),
    ]
