# Generated by Django 3.0.3 on 2020-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200218_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryissue',
            name='title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='dormitory_name',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_first_name',
            field=models.CharField(blank=True, help_text="Enter the first name of the student's male guardian", max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_surname',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Enter First Name', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_country',
            field=models.CharField(blank=True, help_text='Enter home County', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_county',
            field=models.CharField(blank=True, help_text='Enter home County', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_town',
            field=models.CharField(blank=True, help_text='Enter home Town', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_first_name',
            field=models.CharField(blank=True, help_text="Enter the first name of the student's female guardian", max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_surname',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, help_text='Enter Other Name', max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(help_text='Enter Family Name', max_length=35),
        ),
    ]
