# Generated by Django 3.0.3 on 2020-04-25 09:00

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200425_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id', 'surname', 'first_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=True, help_text='Is the student graduated?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=13, null=True, validators=[students.models.validate_phone_length]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=13, null=True, validators=[students.models.validate_phone_length]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[students.models.validate_phone_length]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_phone', 'father_phone'), ('father_email', 'mother_email'), ('student_email', 'mother_email'), ('student_email', 'father_email'), ('student_phone', 'mother_phone'), ('father_phone', 'mother_phone')},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(student_phone=18), name='age_gte_18'),
        ),
    ]
