# Generated by Django 3.0.3 on 2020-04-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200425_1200'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='age_gte_18',
        ),
    ]
