# Generated by Django 3.0.3 on 2020-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200425_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryissue',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='dormitory_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_first_name',
            field=models.CharField(blank=True, help_text="Enter the first name of the student's male guardian", max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Enter First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='health',
            field=models.TextField(blank=True, default='Good', help_text='Enter health status or complications', max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_country',
            field=models.CharField(blank=True, help_text='Enter home County', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_county',
            field=models.CharField(blank=True, help_text='Enter home County', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_town',
            field=models.CharField(blank=True, help_text='Enter home Town', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='Is the student graduated?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_first_name',
            field=models.CharField(blank=True, help_text="Enter the first name of the student's female guardian", max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, help_text='Enter Other Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(help_text='Enter Family Name', max_length=50),
        ),
    ]
