# Generated by Django 3.0.3 on 2020-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200425_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='Has the student graduated?'),
        ),
    ]
