# Generated by Django 3.0.3 on 2020-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200425_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitories',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=50),
        ),
    ]
