# Generated by Django 3.0.3 on 2020-04-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_dormitories_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
