version: "3"

services:
  sch-api-redis:
    container_name: sch-api-redis
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
  nginx2:
    build: ./backend/nginx
    restart: unless-stopped
    container_name: school-nginx-api
    ports:
      - 8001:8001
    depends_on:
      - school-api
    links:
      - school-api
  school-api:
    build: ./backend
    container_name: school-api
    links:
      - sch-api-redis
    depends_on:
      - sch-api-redis
    restart: unless-stopped
    expose:
      - "8001"
    env_file:
      - backend/.env
    command: >
      /bin/sh -c "
      cd backend ; python manage.py makemigrations --merge --noinput
      && python manage.py migrate
      && gunicorn --bind 0.0.0.0:8001 school.wsgi:application
      "
    volumes:
      - .:/code
  frontend:
    build: ./frontend
    container_name: school-frontend
    volumes:
      - /code/node_modules
      - ./code:/frontend
    depends_on:
      - nginx2
  nginx:
    build: ./frontend
    container_name: school-nginx-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - frontend
