# Generated by Django 3.0.3 on 2020-04-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_auto_20200224_2100'),
        ('academics', '0004_auto_20200411_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam_start_date', models.DateField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['exam_start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examinations.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.Subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
