# Generated by Django 3.0.2 on 2020-02-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='classes_involved',
            field=models.ManyToManyField(to='academics.ClassNumeral'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(help_text='Select Subjects', to='academics.Subject'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(help_text='Select Student Members', to='students.Student'),
        ),
        migrations.AddField(
            model_name='club',
            name='teacher_assistant_lead',
            field=models.ManyToManyField(help_text='Select assistant Teacher', related_name='Assistant_Teacher_Leads', to='staff.TeachingStaff'),
        ),
        migrations.AddField(
            model_name='club',
            name='teacher_lead',
            field=models.ManyToManyField(help_text='Select Teacher In Charge', related_name='Teacher_Leads', to='staff.TeachingStaff'),
        ),
        migrations.AddField(
            model_name='classes',
            name='assistant_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_assistantClassTeachers', to='staff.TeachingStaff'),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_numeral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.ClassNumeral'),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classTeachers', to='staff.TeachingStaff'),
        ),
        migrations.AddField(
            model_name='classes',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.Stream'),
        ),
    ]
