# Generated by Django 3.0.2 on 2020-02-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20200202_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('class_numeral', 'stream')},
        ),
    ]
