# Generated by Django 3.0.3 on 2020-04-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20200202_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
