# Generated by Django 3.0.3 on 2020-04-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_auto_20200224_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/teachers/assignments')),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/teachers/assignments')),
                ('file3', models.FileField(blank=True, null=True, upload_to='files/teachers/assignments')),
                ('time_starts', models.DateTimeField()),
                ('time_required', models.DateTimeField()),
                ('parents_notified', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/students/assignments')),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/students/assignments')),
                ('file3', models.FileField(blank=True, null=True, upload_to='files/students/assignments')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assignments.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_last_edited', models.DateTimeField(auto_now=True)),
                ('assignment_submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.AssignmentSubmission')),
            ],
        ),
    ]
