# Generated by Django 3.0.3 on 2020-04-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200224_2100'),
        ('academics', '0004_auto_20200411_0651'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-time_last_edited', '-time_starts']},
        ),
        migrations.AlterModelOptions(
            name='assignmentmarks',
            options={'ordering': ['-time_last_edited', '-marks']},
        ),
        migrations.AlterField(
            model_name='assignmentmarks',
            name='assignment_submitted',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignments.AssignmentSubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('name', 'time_added')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddConstraint(
            model_name='assignmentmarks',
            constraint=models.CheckConstraint(check=models.Q(marks__lte=100), name='marks_lte_100'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='assignmentsubmission',
            order_with_respect_to='assignment',
        ),
        migrations.AddField(
            model_name='assignmentclass',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignment'),
        ),
        migrations.AddField(
            model_name='assignmentclass',
            name='class_ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Classes'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentclass',
            unique_together={('assignment', 'class_ns')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='assignmentclass',
            order_with_respect_to='assignment',
        ),
    ]
