# Generated by Django 3.0.3 on 2020-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20200419_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmarks',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
