# Generated by Django 3.0.3 on 2020-04-19 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentmarks_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentclass',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentclass',
            name='time_last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
